import { Navbar } from "@/components/layout/navbar";
import { Button } from "@/components/ui/button";
import { X } from "lucide-react";
import Link from "next/link";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-black text-zinc-300 selection:bg-indigo-500/30">
            <Navbar />
            <div className="container mx-auto px-6 pt-24 pb-20 max-w-4xl">
                <div className="flex justify-end mb-4">
                    <Button asChild variant="ghost" size="icon" className="hover:bg-white/10 text-zinc-400">
                        <Link href="/">
                            <X className="w-6 h-6" />
                        </Link>
                    </Button>
                </div>
                <h1 className="text-4xl font-bold text-white mb-8">Terms of Service</h1>
                <div className="prose prose-invert max-w-none space-y-8">
                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">1. Execution Responsibility</h2>
                        <p>
                            Aegis provides a runtime environment ("The Engine") for automated execution. You acknowledge that you are solely responsible for the logic, parameters, and risk controls of your algorithms.
                            Aegis Systems Inc. disclaims all liability for trading losses incurred due to strategy variance or market conditions.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">2. No Financial Advice</h2>
                        <p>
                            The Platform is a technical tool for execution and analysis. No feature, indicator, or signal generated by the Platform constitutes financial advice or a recommendation to buy or sell any security.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">3. System Latency & Availability</h2>
                        <p>
                            While we strive for 99.9% uptime and sub-millisecond internal latency, you acknowledge that internet connectivity, broker API availability, and exchange uptime are beyond our control.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-4">4. Compliance</h2>
                        <p>
                            You agree to use Aegis in strict compliance with all applicable regulations (SEBI, NSE/BSE) regarding automated trading.
                            Any attempt to use the platform for market manipulation or spoofing will result in immediate termination.
                        </p>
                    </section>

                    <div className="border border-red-500/20 bg-red-500/5 p-6 rounded-lg mt-8">
                        <h3 className="text-white font-bold mb-2">High Risk Warning</h3>
                        <p className="text-sm text-red-200">
                            Algorithmic trading involves significant risk of capital loss. Past performance of any strategy in simulation is not indicative of future results in live markets.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    )
}
