export const PRICING_CONFIG = {
    LIVE_PRICING_ENABLED: true,
    CURRENCY: "INR",
    PLANS: [
        {
            id: "signals",
            name: "Signals Only",
            label: "Manual Reference",
            price: 1499,
            priceDisplay: "₹1,499",
            description: "Access to real-time trading signals generated by the Aegis system. Manual execution only.",
            sections: [
                {
                    title: "Includes",
                    items: [
                        "Live signal feed (NIFTY, BANKNIFTY, SENSEX)",
                        "Entry price, stop loss, and market targets",
                        "Confidence score and market context",
                        "Intraday signal history",
                        "Mobile and browser alerts (PWA)"
                    ]
                },
                {
                    title: "Does not include",
                    items: [
                        "Broker API connection",
                        "Automated order placement",
                        "Portfolio or position tracking"
                    ],
                    variant: "negative"
                },
                {
                    title: "Intended for",
                    items: ["Users who prefer manual trading with structured signal guidance."],
                    variant: "info"
                }
            ],
            cta: "Start Signals Only",
            href: "/signup?plan=signals",
            color: "zinc",
            status: "active"
        },
        {
            id: "automation",
            name: "Automation + Signals",
            label: "Execution Engine",
            price: 2499,
            priceDisplay: "₹2,499",
            description: "Automated trade execution using the Aegis risk framework, combined with full signal visibility.",
            sections: [
                {
                    title: "Includes",
                    items: [
                        "Everything in Signals Only",
                        "Automated execution via user-provided broker APIs",
                        "Risk-profile–based trade governance",
                        "Real-time dashboard (positions, margin, exposure)",
                        "Auto-disable on risk breach or market close"
                    ]
                },
                {
                    title: "Requirements",
                    items: [
                        "Supported broker API access",
                        "Explicit user consent to enable automation"
                    ],
                    variant: "warning"
                },
                {
                    title: "Notes",
                    items: [
                        "No profit guarantees",
                        "Execution follows predefined system rules only"
                    ],
                    variant: "info"
                }
            ],
            cta: "Enable Automation",
            href: "/signup?plan=automation",
            color: "emerald",
            status: "active"
        },
        {
            id: "managed",
            name: "Managed",
            label: "Guided Onboarding",
            price: 0,
            priceDisplay: "Coming Soon",
            description: "Operational assistance for users who prefer guided onboarding and monitored automation.",
            sections: [
                {
                    title: "Planned scope",
                    items: [
                        "Assisted setup and configuration",
                        "Ongoing operational oversight",
                        "Priority support"
                    ]
                },
                {
                    title: "Status",
                    items: [
                        "Details will be published separately.",
                        "This plan is not currently available."
                    ],
                    variant: "info"
                }
            ],
            cta: "Coming Soon",
            href: "#",
            color: "amber",
            status: "coming_soon"
        }
    ],
    DISCLOSURES: [
        "Trading involves financial risk.",
        "Signals and automation are based on predefined system logic.",
        "Losses are possible. No outcome is guaranteed.",
        "Users retain full control of their broker accounts at all times."
    ]
};
